shadowcaster: true

enabled: true

position:
  x: -20
  y: -20
  z: -20

direction:
  x: -1
  y: 1
  z: 1

type: SPOT_LIGHT

angle: 1.5

attenuation:
  constant: 0.85
  linear: 0
  quadratic: 0

color:
  ambient:
    red: 0.3
    green: 0.3
    blue: 0.3
    alpha: 1

  diffuse:
    red: 0.45
    green: 0.45
    blue: 0.45
    alpha: 1.0

  specular:
    red: 0.2
    green: 0.2
    blue: 0.2
    alpha: 1.0
