require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeshesController do

  # This should return the minimal set of attributes required to create a valid
  # Mesh. As you add validations to Mesh, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeshesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all meshes as @meshes" do
      mesh = Mesh.create! valid_attributes
      get :index, {}, valid_session
      assigns(:meshes).should eq([mesh])
    end
  end

  describe "GET show" do
    it "assigns the requested mesh as @mesh" do
      mesh = Mesh.create! valid_attributes
      get :show, {:id => mesh.to_param}, valid_session
      assigns(:mesh).should eq(mesh)
    end
  end

  describe "GET new" do
    it "assigns a new mesh as @mesh" do
      get :new, {}, valid_session
      assigns(:mesh).should be_a_new(Mesh)
    end
  end

  describe "GET edit" do
    it "assigns the requested mesh as @mesh" do
      mesh = Mesh.create! valid_attributes
      get :edit, {:id => mesh.to_param}, valid_session
      assigns(:mesh).should eq(mesh)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mesh" do
        expect {
          post :create, {:mesh => valid_attributes}, valid_session
        }.to change(Mesh, :count).by(1)
      end

      it "assigns a newly created mesh as @mesh" do
        post :create, {:mesh => valid_attributes}, valid_session
        assigns(:mesh).should be_a(Mesh)
        assigns(:mesh).should be_persisted
      end

      it "redirects to the created mesh" do
        post :create, {:mesh => valid_attributes}, valid_session
        response.should redirect_to(Mesh.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mesh as @mesh" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mesh.any_instance.stub(:save).and_return(false)
        post :create, {:mesh => {}}, valid_session
        assigns(:mesh).should be_a_new(Mesh)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mesh.any_instance.stub(:save).and_return(false)
        post :create, {:mesh => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mesh" do
        mesh = Mesh.create! valid_attributes
        # Assuming there are no other meshes in the database, this
        # specifies that the Mesh created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mesh.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mesh.to_param, :mesh => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mesh as @mesh" do
        mesh = Mesh.create! valid_attributes
        put :update, {:id => mesh.to_param, :mesh => valid_attributes}, valid_session
        assigns(:mesh).should eq(mesh)
      end

      it "redirects to the mesh" do
        mesh = Mesh.create! valid_attributes
        put :update, {:id => mesh.to_param, :mesh => valid_attributes}, valid_session
        response.should redirect_to(mesh)
      end
    end

    describe "with invalid params" do
      it "assigns the mesh as @mesh" do
        mesh = Mesh.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mesh.any_instance.stub(:save).and_return(false)
        put :update, {:id => mesh.to_param, :mesh => {}}, valid_session
        assigns(:mesh).should eq(mesh)
      end

      it "re-renders the 'edit' template" do
        mesh = Mesh.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mesh.any_instance.stub(:save).and_return(false)
        put :update, {:id => mesh.to_param, :mesh => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mesh" do
      mesh = Mesh.create! valid_attributes
      expect {
        delete :destroy, {:id => mesh.to_param}, valid_session
      }.to change(Mesh, :count).by(-1)
    end

    it "redirects to the meshes list" do
      mesh = Mesh.create! valid_attributes
      delete :destroy, {:id => mesh.to_param}, valid_session
      response.should redirect_to(meshes_url)
    end
  end

end
