require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegionStylesController do

  # This should return the minimal set of attributes required to create a valid
  # RegionStyle. As you add validations to RegionStyle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegionStylesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all region_styles as @region_styles" do
      region_style = RegionStyle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:region_styles).should eq([region_style])
    end
  end

  describe "GET show" do
    it "assigns the requested region_style as @region_style" do
      region_style = RegionStyle.create! valid_attributes
      get :show, {:id => region_style.to_param}, valid_session
      assigns(:region_style).should eq(region_style)
    end
  end

  describe "GET new" do
    it "assigns a new region_style as @region_style" do
      get :new, {}, valid_session
      assigns(:region_style).should be_a_new(RegionStyle)
    end
  end

  describe "GET edit" do
    it "assigns the requested region_style as @region_style" do
      region_style = RegionStyle.create! valid_attributes
      get :edit, {:id => region_style.to_param}, valid_session
      assigns(:region_style).should eq(region_style)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RegionStyle" do
        expect {
          post :create, {:region_style => valid_attributes}, valid_session
        }.to change(RegionStyle, :count).by(1)
      end

      it "assigns a newly created region_style as @region_style" do
        post :create, {:region_style => valid_attributes}, valid_session
        assigns(:region_style).should be_a(RegionStyle)
        assigns(:region_style).should be_persisted
      end

      it "redirects to the created region_style" do
        post :create, {:region_style => valid_attributes}, valid_session
        response.should redirect_to(RegionStyle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved region_style as @region_style" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStyle.any_instance.stub(:save).and_return(false)
        post :create, {:region_style => {}}, valid_session
        assigns(:region_style).should be_a_new(RegionStyle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStyle.any_instance.stub(:save).and_return(false)
        post :create, {:region_style => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested region_style" do
        region_style = RegionStyle.create! valid_attributes
        # Assuming there are no other region_styles in the database, this
        # specifies that the RegionStyle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RegionStyle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => region_style.to_param, :region_style => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested region_style as @region_style" do
        region_style = RegionStyle.create! valid_attributes
        put :update, {:id => region_style.to_param, :region_style => valid_attributes}, valid_session
        assigns(:region_style).should eq(region_style)
      end

      it "redirects to the region_style" do
        region_style = RegionStyle.create! valid_attributes
        put :update, {:id => region_style.to_param, :region_style => valid_attributes}, valid_session
        response.should redirect_to(region_style)
      end
    end

    describe "with invalid params" do
      it "assigns the region_style as @region_style" do
        region_style = RegionStyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStyle.any_instance.stub(:save).and_return(false)
        put :update, {:id => region_style.to_param, :region_style => {}}, valid_session
        assigns(:region_style).should eq(region_style)
      end

      it "re-renders the 'edit' template" do
        region_style = RegionStyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStyle.any_instance.stub(:save).and_return(false)
        put :update, {:id => region_style.to_param, :region_style => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested region_style" do
      region_style = RegionStyle.create! valid_attributes
      expect {
        delete :destroy, {:id => region_style.to_param}, valid_session
      }.to change(RegionStyle, :count).by(-1)
    end

    it "redirects to the region_styles list" do
      region_style = RegionStyle.create! valid_attributes
      delete :destroy, {:id => region_style.to_param}, valid_session
      response.should redirect_to(region_styles_url)
    end
  end

end
